name: Continuous integration pipeline

on:
  push:
    branches:
      - master

jobs:
  run-tests-and-upload-coverage-report:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ConorMacBride/install-package@v1
        with:
          brew: lcov

      - uses: futureware-tech/simulator-action@v3
        with:
          mode: 'iPhone 14'

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'


      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        run: dart format . --set-exit-if-changed

      - name: Lint analysis
        run: flutter analyze --no-pub

      - name: Run integration tests
        run: flutter test integration_test --coverage --coverage-path=coverage/integration_coverage_lcov.info

      - name: Run unit tests
        run: flutter test test --coverage --coverage-path=coverage/unit_coverage_lcov.info

      - name: Merge coverage before upload
        run: lcov -a coverage/unit_coverage_lcov.info -a coverage/integration_coverage_lcov.info -o ./coverage/lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info